rxn
rxn ?
? rxn

rxn reset login ?
reset login
reset login

rxn list models ?
rxn list models

rxn interpret recipe ?
rxn interpret recipe 'my_recipe.txt'
rxn interpret recipe 'A solution of ((1S,2S)-1-{[(methoxymethyl-biphenyl-4-yl)-(2-pyridin-2-yl-cyclopropanecarbonyl)-amino]-methyl}-2-methyl-butyl)-carbamic acid tert-butyl ester (25 mg, 0.045 mmol) and dichloromethane (4 mL) was treated with a solution of HCl in dioxane (4 N, 0.5 mL) and the resulting reaction mixture was maintained at room temperature for 12 h. The reaction was then concentrated to dryness to afford (1R,2R)-2-pyridin-2-yl-cyclopropanecarboxylic acid ((2S,3S)-2-amino-3-methylpentyl)-(methoxymethyl-biphenyl-4-yl)-amide (18 mg, 95% yield) as a white solid.'

rxn predict retrosynthesis ?
rxn predict retrosynthesis 'BrCCc1cccc2c(Br)c3ccccc3cc12' using (max_steps=3)
rxn predict retrosynthesis 'BrCCc1cccc2c(Br)c3ccccc3cc12' using (max_steps=3)
rxn predict retrosynthesis 'BrCCc1cccc2c(Br)c3ccccc3cc12' using (max_steps=3) no cache
rxn predict retrosynthesis 'ABCDEF' using (max_steps=3)

rxn predict reaction ?
rxn predict reaction 'BrBr.c1ccc2cc3ccccc3cc2c1CCO'
rxn predict reaction 'BrBr.c1ccc2cc3ccccc3cc2c1CCO'
rxn predict reaction 'BrBr.c1ccc2cc3ccccc3cc2c1CCO' no cache

rxn predict reactions from list ['BrBr.c1ccc2cc3ccccc3cc2c1CCO' , 'BrBr.c1ccc2cc3ccccc3cc2c1']
rxn predict reactions from list ['BrBr.c1ccc2cc3ccccc3cc2c1CCO' , 'BrBr.c1ccc2cc3ccccc3cc2c1']
rxn predict reactions from list ['BrBr.c1ccc2cc3ccccc3cc2c1CCO' , 'BrBr.c1ccc2cc3ccccc3cc2c1'] no cache

rxn predict reactions from file 'my_reactions.csv'
rxn predict reactions from file 'my_reactions.csv'
rxn predict reactions from file 'my_reactions.csv' no cache

rxn predict reactions from dataframe my_reactions_df
rxn predict reactions from dataframe my_reactions_df
rxn predict reactions from dataframe my_reactions_df no cache